baseURL = "https://bethanysdatenight.com/"
languageCode = "en-us"
theme = "site-theme"
title = "Bethany's Father Daughter Date Night"
[menu]
    [[menu.desktop]]
    identifier = "about"
    name       = "About Us"
    url        = "/about-us"
    weight     = 1

    [[menu.desktop]]
    identifier = "pastRecipients"
    name       = "Past Recipients"
    url        = "/past-recipients"
    weight     = 2

    [[menu.desktop]]
    identifier = "contactUs"
    name       = "Contact Us"
    url        = "/contact-us"
    weight     = 3

    [[menu.mobile]]
    identifier = "about"
    name       = "About Us"
    url        = "/about-us"
    weight     = 1

    [[menu.mobile]]
    identifier = "pastRecipients"
    name       = "Past Recipients"
    url        = "/past-recipients"
    weight     = 2

    [[menu.mobile]]
    identifier = "contactUs"
    name       = "Contact Us"
    url        = "/contact-us"
    weight     = 3

[params]
categories = ["",""]
description = "An annual date night for Daddies and Daughters in honor of Sarah Bethany Green."
email = "bethanysfatherdaughter@gmail.com"
cloudinary_url = "https://res.cloudinary.com/pioneer-design/image/upload"

[params.Logos]
logo = "/v1575904760/Bethany%20Father%20Daughter/BFDDN.Logo.White_jajjrl.svg"

[params.social]
facebook = "https://www.facebook.com/pages/category/Community-Organization/Bethanys-Father-Daughter-Date-Night-156944461181968/"