---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Homepage
  create: all
  match: "*"
- type: document
  path: themes/site-theme/data/past_recipiants.toml
  label: Past Recipients
- type: directory
  path: content/pages
  label: Pages
  create: all
  match: "**/*"
upload_dir: Bethany Father Daughter
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.53'
